/**
 *
 * Class HumResource - class that holds information on HumResource table in database
 *
 * Create by Jonas W. Kohls 11 Nov 2019
 */

import java.sql.*;

public class HumResource {

    DataAccessObject dao = new DataAccessObject();                  //JDBC Data Access Object
    String tableName;                                               //String of object's specific table name
    private ResultSet rs;                                           //JDBC Result set to get string of generated by query
    private String result;                                          //String to hold processed result
    private int hridProcessed;                                      //Int representing hrid in the database

    //HumResource Constructor
    public HumResource() {
        tableName = "HumResource ";
    }

    //Method to insert data into the HumResource table in the database
    public int insert(String name, String address, String phone, Double latitude, Double longitude, String type, String desc, String hours) {
        hridProcessed = createHRID();
        dao.connect();
        dao.setAutoCommit(false);
        dao.executeSQLNonQuery("INSERT INTO " + tableName + "VALUES (" + hridProcessed + ", '" + name + "', '" +
                address + "', '" + phone + "', " + latitude + ", " + longitude + ", '" + type + "', '" + desc + "', '" +
                hours + "')");
        dao.commit();
        dao.disconnect();
        return hridProcessed;
    }

    //Method to update data from the HumResource table in the database
    public void update(int hrid, String name, String address, String phone, Double latitude, Double longitude, String type, String desc, String hours) {
        dao.connect();
        dao.setAutoCommit(false);
        dao.executeSQLNonQuery("UPDATE " + tableName + "SET HRName = '" + name + "', HRAddressString = '"
                + address + "', HRPhoneNumber = '" + phone + "', HRLatitude = " + latitude + ", HRLongitude = " +
                longitude + ", HRType = '" + type + "', HRDesc = '" + desc + "', HROpenHoursString = '" + hours +
                "' WHERE HRID = " + hrid);
        dao.commit();
        dao.disconnect();
    }

    //Method to delete data from HumResource table and another table based on a table name and an id parameter in the database
    public void delete(String tableName, int hrid) {
        dao.connect();
        dao.setAutoCommit(false);
        dao.executeSQLNonQuery("DELETE FROM " + tableName + "WHERE HRID = " + hrid);
        dao.executeSQLNonQuery("DELETE FROM " + this.tableName + "WHERE HRID = " + hrid);
        dao.commit();
        dao.disconnect();
    }

    //Method to display all data with a specific id from a table name
    public String displayHRID(String tableName, int hrid) {
        dao.connect();
        dao.setAutoCommit(false);
        rs = dao.executeSQLQuery("SELECT * FROM " + tableName + "WHERE HRID = " + hrid);
        result = dao.processResultSet(rs);
        dao.disconnect();
        return result;
    }

    //Method to get the highest HRID in the database, convert it into an int, and return one higher than it
    private int createHRID() {
        dao.connect();
        dao.setAutoCommit(false);
        rs = dao.executeSQLQuery("Select MAX(HRID) FROM " + tableName);
        result = dao.processResultSet(rs);
        hridProcessed = Integer.parseInt(result);
        dao.disconnect();
        return hridProcessed + 1;
    }
}
